import { Router } from 'express'; import { execFileSync } from 'node:child_process'; import path from 'node:path'; import fs from 'node:fs';
import { search } from '../services/programCaseSearchRetrieval/searchService'; import { CorpusType, SearchMethod } from '../services/programCaseSearchRetrieval/types'; import { EVALUATION, readJson, RETRIEVAL } from '../services/programCaseSearchRetrieval/artifacts'; import { buildQueries, metrics, saveLabel, EVALUATION_VERSION } from '../services/programCaseSearchEvaluation/evaluation';
const router=Router(); const methods:SearchMethod[]=['BM25','DENSE','HYBRID','HYBRID_TARGETED'];
router.use((_req,res,next)=>{res.setHeader('Cache-Control','no-store');if(process.env.NODE_ENV==='production'&&process.env.ENABLE_PROGRAM_CASE_SEARCH_EVALUATION!=='true')return res.status(404).json({error:'Search evaluation is disabled'});next()});
const text=(value:unknown,max=500)=>typeof value==='string'?value.trim().slice(0,max):'';
function queryEmbedding(query:string):number[]{const backend=path.resolve(__dirname,'../..');const python=process.platform==='win32'?path.join(backend,'.venv','Scripts','python.exe'):path.join(backend,'.venv','bin','python');const output=execFileSync(python,['-m','program_case_semantic_search.artifact_cli','--input','unused','--output','unused','--corpus-type','CORE','--query',query],{cwd:path.join(backend,'python'),encoding:'utf8',env:{...process.env,PYTHONPATH:path.join(backend,'python'),HF_HUB_OFFLINE:'1',TRANSFORMERS_OFFLINE:'1',PYTHONIOENCODING:'utf-8'}});return JSON.parse(output).embedding}
router.get('/summary',(_req,res)=>{const exists=(name:string)=>fs.existsSync(path.join(RETRIEVAL,name));res.json({corpus:{core:280,safe:280},artifacts:{bm25Core:exists('bm25-core-index.json'),bm25Safe:exists('bm25-safe-index.json'),embeddingsCore:exists('core-embeddings.json'),embeddingsSafe:exists('safe-embeddings.json')},evaluation:metrics()})});
router.get('/methods',(_req,res)=>res.json({methods,corpora:['CORE','SAFE'],rrf:{version:'rrf-v1',constant:60,bm25CandidateLimit:50,denseCandidateLimit:50,finalLimit:20},chunkBaseline:{method:'CHUNK_P0',endpoint:'/api/program-case/semantic-search',unit:'ProgramCaseDocumentChunk',readOnly:true}}));
router.get('/search',(req,res)=>{try{const q=text(req.query.q);if(!q)return res.status(400).json({error:'q is required'});const method=text(req.query.method).toUpperCase() as SearchMethod;const corpusType=text(req.query.corpus).toUpperCase() as CorpusType;const limit=Number(req.query.limit??5);if(!methods.includes(method)||!['CORE','SAFE'].includes(corpusType)||!Number.isInteger(limit)||limit<1||limit>20)return res.status(400).json({error:'invalid method, corpus, or limit'});const embedding=method==='BM25'?undefined:queryEmbedding(q);const results=search({query:q,method,corpusType,limit,queryEmbedding:embedding,targetAgeGroup:text(req.query.targetAgeGroup),grade:req.query.grade==null?undefined:Number(req.query.grade)});res.json({query:q,method,corpusType,top1Top2Margin:results.length>1&&results[0].similarity!=null&&results[1].similarity!=null?results[0].similarity-results[1].similarity:null,thresholdPolicy:'NOT_SET_MVP',results})}catch(error){res.status(503).json({error:error instanceof Error?error.message:'search unavailable'})}});
router.get('/queries',(_req,res)=>{let items;try{items=readJson(path.join(EVALUATION,'queries.json'))}catch{items=buildQueries()}res.json({items})});
router.get('/pool',(_req,res)=>{let items:unknown[]=[];try{items=readJson<unknown[]>(path.join(EVALUATION,'pooled-results.json'))}catch{}res.json({items})});
router.get('/evaluations',(_req,res)=>{let items:unknown[]=[];try{items=readJson<unknown[]>(path.join(EVALUATION,'relevance-labels.json'))}catch{}res.json({items})});
router.post('/evaluations',(req,res)=>{try{const relevance=Number(req.body?.relevance);const queryId=text(req.body?.queryId,100),resultKey=text(req.body?.resultKey,200),groupId=text(req.body?.groupId,200);if(!queryId||!resultKey||!groupId)return res.status(400).json({error:'queryId, resultKey and groupId are required'});res.status(201).json(saveLabel({queryId,resultKey,groupId,relevance,reviewerNote:text(req.body?.reviewerNote,1000),evaluationVersion:EVALUATION_VERSION,reviewedAt:new Date().toISOString()}))}catch(error){res.status(400).json({error:error instanceof Error?error.message:'invalid evaluation'})}});
router.get('/metrics',(_req,res)=>res.json(metrics())); export default router;
