export type AttachmentErrorCode =
  | 'INVALID_URL'
  | 'HOST_NOT_ALLOWED'
  | 'PRIVATE_ADDRESS_BLOCKED'
  | 'REDIRECT_LIMIT_EXCEEDED'
  | 'DOWNLOAD_TIMEOUT'
  | 'DOWNLOAD_FAILED'
  | 'FILE_TOO_LARGE'
  | 'EMPTY_FILE'
  | 'HTML_RESPONSE'
  | 'UNSUPPORTED_FILE_TYPE'
  | 'FILE_TYPE_MISMATCH'
  | 'PDF_PARSE_FAILED'
  | 'OCR_REQUIRED'
  | 'PDF_RENDERER_UNAVAILABLE'
  | 'PDF_RENDERER_VERSION_FAILED'
  | 'PDF_RENDER_TIMEOUT'
  | 'PDF_RENDER_FAILED'
  | 'PDF_RENDER_OUTPUT_MISSING'
  | 'PDF_RENDER_OUTPUT_TOO_LARGE'
  | 'PDF_RENDER_OUTPUT_INVALID'
  | 'PDF_PAGE_NUMBER_INVALID'
  | 'PDF_PAGE_LIMIT_EXCEEDED'
  | 'PDF_OCR_PAGE_RESULT_MISSING'
  | 'PDF_OCR_PAGE_NUMBER_DUPLICATED'
  | 'PDF_OCR_PAGE_NUMBER_OUT_OF_RANGE'
  | 'PDF_OCR_PAGE_COUNT_INVALID'
  | 'PDF_OCR_MERGE_FAILED'
  | 'PDF_OCR_CANDIDATE_MISSING'
  | 'PDF_OCR_CANDIDATE_INVALID'
  | 'SUBPROCESS_NOT_FOUND'
  | 'SUBPROCESS_TIMEOUT'
  | 'SUBPROCESS_OUTPUT_LIMIT_EXCEEDED'
  | 'SUBPROCESS_EXIT_FAILED'
  | 'SUBPROCESS_TERMINATED'
  | 'CLOVA_OCR_DISABLED'
  | 'CLOVA_OCR_CONFIG_MISSING'
  | 'CLOVA_OCR_AUTH_FAILED'
  | 'CLOVA_OCR_FORBIDDEN'
  | 'CLOVA_OCR_RATE_LIMITED'
  | 'CLOVA_OCR_TIMEOUT'
  | 'CLOVA_OCR_REQUEST_INVALID'
  | 'CLOVA_OCR_REQUEST_FAILED'
  | 'CLOVA_OCR_SERVER_ERROR'
  | 'CLOVA_OCR_RESPONSE_TOO_LARGE'
  | 'CLOVA_OCR_RESPONSE_INVALID'
  | 'CLOVA_OCR_IMAGE_FAILED'
  | 'IMAGE_DECODE_FAILED'
  | 'IMAGE_DIMENSIONS_MISSING'
  | 'IMAGE_DIMENSION_LIMIT_EXCEEDED'
  | 'IMAGE_PIXEL_LIMIT_EXCEEDED'
  | 'IMAGE_DECODE_MEMORY_LIMIT_EXCEEDED'
  | 'IMAGE_ANIMATION_UNSUPPORTED'
  | 'IMAGE_FORMAT_UNSUPPORTED'
  | 'IMAGE_PREPROCESS_FAILED'
  | 'CHECKSUM_DONOR_CONFLICT'
  | 'HWP_CONTAINER_INVALID'
  | 'HWP_LIMIT_EXCEEDED'
  | 'HWP_UNSUPPORTED_HWPX'
  | 'HWP_SIGNATURE_MISMATCH'
  | 'HWP_ENCRYPTED'
  | 'HWP_DISTRIBUTION_DOCUMENT'
  | 'HWP_BODY_TEXT_MISSING'
  | 'HWP_EXTRACTOR_NOT_AVAILABLE'
  | 'HWP_EXTRACTION_TIMEOUT'
  | 'HWP_EXTRACTION_PROCESS_FAILED'
  | 'HWP_OUTPUT_MISSING'
  | 'HWP_OUTPUT_TOO_LARGE'
  | 'HWP_OUTPUT_EMPTY'
  | 'HWP_OUTPUT_INVALID'
  | 'HWPX_CONTAINER_INVALID'
  | 'HWPX_LIMIT_EXCEEDED'
  | 'TEMP_FILE_CLEANUP_FAILED'
  | 'UNKNOWN_ERROR';

export class AttachmentProcessingError extends Error {
  constructor(
    public readonly code: AttachmentErrorCode,
    message: string,
    public readonly retryable = false,
  ) {
    super(message);
    this.name = 'AttachmentProcessingError';
  }
}

export function safeAttachmentError(error: unknown) {
  if (error instanceof AttachmentProcessingError) return error;
  return new AttachmentProcessingError('UNKNOWN_ERROR', 'Unexpected attachment processing failure.');
}
